server:
  port: 8001
spring:
  profiles:
    active: enc
  redis:
    # enc profile
    # host: xx.xx.xx.xx
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000
      shutdown-timeout: 0
    database: 0
    timeout: 5000
